WebAppSchool/Models/ErrorViewModel.cs
namespace WebAppSchool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppSchool/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Context;

namespace WebAppSchool.Controllers
{
    public class CourseController : Controller
    {
        private SchoolContext context = new SchoolContext();
        public IActionResult Index()
        {
            var list = context.Courses.ToList();    
            return View(list);
        }
    }
}

WebAppSchool/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppSchool.Models;

namespace WebAppSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppSchool/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Context;

namespace WebAppSchool.Controllers
{
    public class StudentController : Controller
    {
        private SchoolContext _db = new SchoolContext();
        public IActionResult Index()
        {
            var list = _db.Students.ToList();
            return View(list);
        }
    }
}

WebAppSchool/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Context;
using Models.Entities;

namespace WebAppSchool.Controllers
{
    public class TeacherController : Controller
    {
        private SchoolContext _db = new SchoolContext();
        public IActionResult List()
        {
            var list = _db.Teatchers.ToList();
            return View("Index",list);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Teacher teacher)
        {
            _db.Teatchers.Add(teacher);
            _db.SaveChanges();
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var selected = _db.Teatchers.FirstOrDefault(i => i.TeacherId == Id);
            return View(selected);
        }

        [HttpPost]
        public IActionResult Edit(Teacher teacher)
        {
            _db.Teatchers.Update(teacher);
            _db.SaveChanges();
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var teacher = _db.Teatchers.Find(id);
            if (teacher == null)
            {
                return NotFound();
            }

            _db.Teatchers.Remove(teacher);
            _db.SaveChanges();

            return RedirectToAction("List");
        }


    }
}

WebAppSchool/Views/Course/Index.cshtml
@using Models.Entities
@model List<Courses>
<nav>
    <a class="btn btn-success" href="@Url.Action("Index", "Teacher")">View Teachers</a>
    <a class="btn btn-success" href="@Url.Action("Index", "Student")">View Students</a>
    <a class="btn btn-success" href="@Url.Action("Index", "Course")">View Courses</a>
</nav>
<h1>Courses List</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Course Name</th>
            <th>Teacher</th>
            <th>Classroom</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Teatcher.Name</td>
                <td>@item.Classrooms.Name</td>
            </tr>
        }
    </tbody>
</table>

WebAppSchool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAppSchool/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>

    <!-- Mes styles-->
    <link rel="stylesheet" href="css/style.css">


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/dashboard.css" />
    @RenderSection("styles", false)
</head>

<body>

    <!-- My Side Barre -->
    <div class="sideBarre">
        <div class="sideBarre__logo">
            <div class="sideBarre__cercle">
            </div>
            <h1>serein</h1>
        </div>
        <div class="sideBarre__menu">
            <ul>
                <li>
                    <a asp-controller="Teacher"
                    asp-action="List">
                    Get Teacher Teacher
                </a>
                </li>


                <li>
                    <a asp-controller="Teacher"
                       asp-action="add">
                       Add Teacher</a>
                </li>
               



                <li><a href="#">Form Elements</a></li>
                <li><a href="#">Editors</a></li>
                <li><a href="#">Charts</a></li>
                <li><a href="#">Tables</a></li>
                <li><a href="#">Popups</a></li>
                <li><a href="#">Notifications</a></li>
                <li><a href="#">Icons</a></li>
                <li><a href="#">Maps</a></li>
                <li><a href="#">User Pages</a></li>
                <li><a href="#">Error Pages</a></li>
            </ul>
        </div>
    </div>

    <!-- My Main Content -->
    <div class="mainContent">
        <nav>
            <div class="user">
            </div>
        </nav>

        <!-- My Box Content -->
        <div class="boxContent">
            @RenderBody()
        </div>
    </div>

</body>

</html>

WebAppSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppSchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppSchool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebAppSchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppSchool/Views/Student/Index.cshtml
@using Models.Entities;
@model List<Student>
<nav>
    <a class="btn btn-success" href="@Url.Action("Index", "Teacher")">View Teachers</a>
    <a class="btn btn-success" href="@Url.Action("Index", "Student")">View Students</a>
    <a class="btn btn-success" href="@Url.Action("Index", "Course")">View Coursees</a>
</nav>

<h1>Our Students</h1>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Student ID</th>
            <th>Name</th>
            <th>Date of Birth</th>
            <th>Email</th>
            <th>Phone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.Name</td>
                <td>@student.DateOfBirth.ToShortDateString()</td>
                <td>@student.Email</td>
                <td>@student.Phone</td>
            </tr>
        }
    </tbody>

</table>


<h1>Use Lazy lodaing </h1>
<ul class="list-group">

@foreach (var student in Model)
{

        <li class="list-group-item active">@student.StudentId</li>
        <li class="list-group-item">@student.Name</li>
        <li class="list-group-item">@student.DateOfBirth.ToShortDateString()</li>
        <li class="list-group-item">@student.Email</li>
        <li class="list-group-item">@student.Phone</li>

        <h3>Attendances Of @student.Name</h3>
        @foreach (var Attend in student.Attendances)
        {
            <ul class="list-group">
            <li>@Attend.Student.Name </li>
            <li>@Attend.Courses.Name</li>
            <li>@Attend.Date.ToShortDateString()</li>
            <li>@(Attend.IsPresent ? "Present" : "Absent")</li>
            </ul>
        }

    }

</ul>

WebAppSchool/Views/Teacher/Edit.cshtml
@{
    Layout = "_AdminLayout";
}
@model Teacher

<form asp-controller="teacher" asp-action="Edit" method="post">
    <!-- Hidden TeacherId -->
    <input class="form-control" asp-for="TeacherId" hidden />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input class="form-control" asp-for="Name" />
    </div>

    <div class="mb-3">
        <label asp-for="Subject" class="form-label"></label>
        <input class="form-control" asp-for="Subject" />
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input class="form-control" asp-for="Email" />
    </div>

    <div class="mb-3">
        <label asp-for="phone" class="form-label"></label>
        <input class="form-control" asp-for="phone" />
    </div>

    <input class="btn btn-info" type="submit" value="Edit Teacher" />
</form>

WebAppSchool/Views/Teacher/Index.cshtml
@using Models.Entities;
@model List<Teacher>
<h1>Our Teacher</h1>

<table class="table table-dark table-bordered table-striped">
    <thead>
        <tr>
            <th>Teacher ID</th>
            <th>Name</th>
            <th>Date of Birth</th>
            <th>Email</th>
            <th>Phone</th>
            <th scope="col">
                Edit
            </th>
            <th scope="col">
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var teacher in Model)
        {
            <tr>
                <td>@teacher.TeacherId</td>
                <td>@teacher.Name</td>
                <td>@teacher.Subject</td>
                <td>@teacher.Email</td>
                <td>@teacher.phone</td>
                <td>
                    <a 
                        asp-action="edit" 
                        asp-controller="Teacher"
                        asp-route-Id="@teacher.TeacherId" 
                    >Edit </a>
                </td>
                <td>
                    <a asp-action="Delete"
                       asp-controller="Teacher"
                       asp-route-Id="@teacher.TeacherId">Delete </a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebAppSchool/Views/Teacher/add.cshtml
@{
    Layout = "_AdminLayout";
}
@model Teacher

<form asp-controller="teacher" asp-action="add" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input class="form-control" asp-for="Name" />
    </div>

    <div class="mb-3">
        <label asp-for="Subject" class="form-label"></label>
        <input class="form-control" asp-for="Subject" />
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input class="form-control" asp-for="Email" />
    </div>

    <div class="mb-3">
        <label asp-for="phone" class="form-label"></label>
        <input class="form-control" asp-for="phone" />
    </div>

    <input class="btn btn-info" type="submit" value="Add Teacher" />
</form>